[phases.setup]
nixPkgs = ["sqlite"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.start]
cmd = "python main.py"
